import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, } from "@/components/ui/table";
import { Pagination, PaginationContent, PaginationItem, PaginationNext, PaginationPrevious, } from "@/components/ui/pagination";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertSeverityBadge } from "./AlertSeverityBadge";
import { AlertStatusBadge } from "./AlertStatusBadge";
import { formatRelative } from "@/lib/utils";
export function AlertTable({ data, total = 0, offset, limit, onPageChange, isLoading }) {
    const navigate = useNavigate();
    const currentPage = Math.floor(offset / limit) + 1;
    const totalPages = Math.max(1, Math.ceil(total / limit));
    if (isLoading) {
        return (_jsx("div", { className: "rounded-md border", children: _jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { children: [_jsx(TableHead, { children: "Severity" }), _jsx(TableHead, { children: "Name" }), _jsx(TableHead, { children: "Status" }), _jsx(TableHead, { children: "Rule" }), _jsx(TableHead, { children: "Created" })] }) }), _jsx(TableBody, { children: Array.from({ length: 6 }).map((_, i) => (_jsxs(TableRow, { children: [_jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-16" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-48" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-20" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-32" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-24" }) })] }, i))) })] }) }));
    }
    if (!data || data.length === 0) {
        return (_jsx("div", { className: "rounded-md border", children: _jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { children: [_jsx(TableHead, { children: "Severity" }), _jsx(TableHead, { children: "Name" }), _jsx(TableHead, { children: "Status" }), _jsx(TableHead, { children: "Rule" }), _jsx(TableHead, { children: "Created" })] }) }), _jsx(TableBody, { children: _jsx(TableRow, { children: _jsx(TableCell, { colSpan: 5, className: "text-center py-8 text-muted-foreground", children: "No alerts match your filters." }) }) })] }) }));
    }
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "rounded-md border", children: _jsxs(Table, { children: [_jsx(TableHeader, { children: _jsxs(TableRow, { children: [_jsx(TableHead, { children: "Severity" }), _jsx(TableHead, { children: "Name" }), _jsx(TableHead, { children: "Status" }), _jsx(TableHead, { children: "Rule" }), _jsx(TableHead, { children: "Created" })] }) }), _jsx(TableBody, { children: data.map((alert) => (_jsxs(TableRow, { className: "cursor-pointer hover:bg-muted/50", onClick: () => void navigate(`/alerts/${alert.id}`), children: [_jsx(TableCell, { children: _jsx(AlertSeverityBadge, { severity: alert.severity }) }), _jsx(TableCell, { className: "font-medium max-w-xs truncate", children: alert.name }), _jsx(TableCell, { children: _jsx(AlertStatusBadge, { status: alert.status }) }), _jsx(TableCell, { className: "text-muted-foreground", children: alert.rule_name ?? "—" }), _jsx(TableCell, { className: "text-muted-foreground text-sm", children: formatRelative(alert.created_at) })] }, alert.id))) })] }) }), _jsxs("div", { className: "flex items-center justify-between text-sm text-muted-foreground", children: [_jsxs("span", { children: ["Showing ", offset + 1, "\u2013", Math.min(offset + limit, total), " of ", total] }), _jsx(Pagination, { children: _jsxs(PaginationContent, { children: [_jsx(PaginationItem, { children: _jsx(PaginationPrevious, { onClick: () => onPageChange(Math.max(0, offset - limit)), "aria-disabled": currentPage <= 1, className: currentPage <= 1 ? "pointer-events-none opacity-50" : "cursor-pointer" }) }), _jsx(PaginationItem, { children: _jsxs("span", { className: "px-3 py-1", children: ["Page ", currentPage, " of ", totalPages] }) }), _jsx(PaginationItem, { children: _jsx(PaginationNext, { onClick: () => onPageChange(offset + limit), "aria-disabled": currentPage >= totalPages, className: currentPage >= totalPages ? "pointer-events-none opacity-50" : "cursor-pointer" }) })] }) })] })] }));
}
