apiVersion: v1
kind: Service
metadata:
  name: umbrella-agent-runtime
  namespace: umbrella-ui
spec:
  selector:
    app: umbrella-agent-runtime
  ports:
    - name: http
      port: 8001
      targetPort: 8001
