apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umbrella-ui
  namespace: umbrella-ui
  labels:
    app: umbrella-ui
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: umbrella-ui-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umbrella-ui-frontend
                port:
                  number: 80
