import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Separator } from "@/components/ui/separator";
import { ParticipantList } from "./ParticipantList";
import { AudioPlayer } from "./AudioPlayer";
import { EnrichmentPanel } from "./EnrichmentPanel";
import { formatDateTime } from "@/lib/utils";
export function MessageDisplay({ message, esIndex }) {
    return (_jsxs("div", { className: "space-y-4 text-sm", children: [_jsxs("div", { className: "flex flex-wrap gap-x-6 gap-y-1 text-muted-foreground", children: [_jsxs("span", { children: ["Channel: ", _jsx("span", { className: "text-foreground font-medium capitalize", children: message.channel })] }), message.direction && (_jsxs("span", { children: ["Direction: ", _jsx("span", { className: "text-foreground font-medium capitalize", children: message.direction })] })), _jsxs("span", { children: ["Timestamp: ", _jsx("span", { className: "text-foreground", children: formatDateTime(message.timestamp) })] })] }), _jsx(Separator, {}), _jsxs("div", { children: [_jsx("h4", { className: "font-medium mb-2", children: "Participants" }), _jsx(ParticipantList, { participants: message.participants })] }), (message.body_text ?? message.transcript ?? message.translated_text ?? message.audio_ref) && (_jsxs(_Fragment, { children: [_jsx(Separator, {}), _jsxs("div", { children: [_jsx("h4", { className: "font-medium mb-2", children: "Content" }), _jsxs("div", { className: "space-y-3", children: [message.body_text && (_jsx("div", { children: _jsx("p", { className: "whitespace-pre-wrap", children: message.body_text }) })), message.transcript && (_jsxs("div", { children: [_jsx("p", { className: "text-muted-foreground text-xs uppercase tracking-wide mb-1", children: "Transcript" }), _jsx("p", { className: "whitespace-pre-wrap", children: message.transcript })] })), message.translated_text && (_jsxs("div", { children: [_jsxs("p", { className: "text-muted-foreground text-xs uppercase tracking-wide mb-1", children: ["Translation ", message.language ? `(from ${message.language})` : ""] }), _jsx("p", { className: "whitespace-pre-wrap", children: message.translated_text })] })), message.audio_ref && (_jsxs("div", { children: [_jsx("p", { className: "text-muted-foreground text-xs uppercase tracking-wide mb-1", children: "Audio" }), _jsx(AudioPlayer, { esIndex: esIndex, docId: message.message_id })] }))] })] })] })), message.attachments.length > 0 && (_jsxs(_Fragment, { children: [_jsx(Separator, {}), _jsxs("div", { children: [_jsxs("h4", { className: "font-medium mb-2", children: ["Attachments (", message.attachments.length, ")"] }), _jsx("ul", { className: "space-y-1", children: message.attachments.map((a, i) => (_jsxs("li", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-medium", children: a.name }), _jsx("span", { className: "text-muted-foreground text-xs", children: a.content_type })] }, i))) })] })] })), _jsx(Separator, {}), _jsxs("div", { children: [_jsx("h4", { className: "font-medium mb-2", children: "Enrichments" }), _jsx(EnrichmentPanel, { message: message })] })] }));
}
